import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#F5F5F5" },
  container: { flex: 1 },
  map: { flex: 1 },
  slotContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "transparent",
  },
  searchButton: {
    position: "absolute",
    bottom: 90,
    alignSelf: "center",
    backgroundColor: "#2E7D32",
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 25,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 5,
  },
  searchButtonText: {
    color: "#FFFFFF",
    fontWeight: "600",
    fontSize: 16,
    textTransform: "uppercase",
  },
  calloutTitle: {
    fontWeight: "bold",
    fontSize: 16,
    color: "#2E7D32",
    marginBottom: 4,
  },
  menuButton: {
    position: "absolute",
    bottom: 20,
    right: 20,
    backgroundColor: "#FFCA28",
    padding: 12,
    borderRadius: 50,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 5,
  },
  ownerButton: {
    position: "absolute",
    bottom: 80,
    right: 20,
    backgroundColor: "#FFCA28",
    padding: 12,
    borderRadius: 50,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 5,
  },
  overlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.4)",
  },
  sidebar: {
    position: "absolute",
    top: 50,
    left: 0,
    width: 250,
    height: "90%",
    backgroundColor: "rgba(255, 255, 255, 0.4)",
    shadowColor: "#000",
    shadowOffset: { width: 2, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 5,
    elevation: 10,
    borderTopRightRadius: 20,
    borderBottomRightRadius: 20,
  },
  sidebarGradient: {
    padding: 20,
    borderTopRightRadius: 20,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    // backgroundColor: "rgb(255, 255, 255)",
  },
  sidebarHeader: { alignItems: "center" },
  profileImage: {
    width: 70,
    height: 70,
    borderRadius: 35,
    borderWidth: 3,
    borderColor: "#FFCA28",
    marginBottom: 15,
  },
  sidebarText: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#FFFFFF",
    textAlign: "center",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  sidebarLinks: { flex: 1, paddingVertical: 10, paddingHorizontal: 15 },
  sidebarButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 15,
    borderRadius: 10,
    backgroundColor: "#F5F5F5",
    marginVertical: 5,
  },
  sidebarLinkText: {
    fontSize: 16,
    color: "#333",
    fontWeight: "500",
  },
  icon: { marginRight: 10 },
  divider: { height: 1, backgroundColor: "#E0E0E0", marginVertical: 5 },
  sidebarFooter: { padding: 15, borderTopWidth: 1, borderTopColor: "#E0E0E0" },
  logoutButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#D32F2F",
    paddingVertical: 12,
    paddingHorizontal: 15,
    borderRadius: 10,
    justifyContent: "center",
  },
  logoutText: { fontSize: 16, color: "#FFFFFF", fontWeight: "600" },
});
